# NLP - Natural Language Processing
## Fake News Detection Project - Using Hash Vector


### Import relevent libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
import matplotlib.pyplot as pyplot

### Data Collection

In [2]:
raw_dataset = pd.read_csv('news.csv', index_col=None)
raw_dataset

Unnamed: 0                                              title  \
0           8476                       You Can Smell Hillary’s Fear   
1          10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2           3608        Kerry to go to Paris in gesture of sympathy   
3          10142  Bernie supporters on Twitter erupt in anger ag...   
4            875   The Battle of New York: Why This Primary Matters   
...          ...                                                ...   
6330        4490  State Department says it can't find emails fro...   
6331        8062  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...   
6332        8622  Anti-Trump Protesters Are Tools of the Oligarc...   
6333        4021  In Ethiopia, Obama seeks progress on peace, se...   
6334        4330  Jeb Bush Is Suddenly Attacking Trump. Here's W...   

                                                   text label  
0     Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1     Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2     U.S. Secretary of State John F. Kerry said Mon...  REAL  
3     — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4     It's primary day in New York and front-runners...  REAL  
...                                                 ...   ...  
6330  The State Department told the Republican Natio...  REAL  
6331  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...  FAKE  
6332   Anti-Trump Protesters Are Tools of the Oligar...  FAKE  
6333  ADDIS ABABA, Ethiopia —President Obama convene...  REAL  
6334  Jeb Bush Is Suddenly Attacking Trump. Here's W...  REAL  

[6335 rows x 4 columns]

### Data Preprocessing

In [3]:
dataset = raw_dataset.drop('Unnamed: 0',axis=1)
dataset

title  \
0                          You Can Smell Hillary’s Fear   
1     Watch The Exact Moment Paul Ryan Committed Pol...   
2           Kerry to go to Paris in gesture of sympathy   
3     Bernie supporters on Twitter erupt in anger ag...   
4      The Battle of New York: Why This Primary Matters   
...                                                 ...   
6330  State Department says it can't find emails fro...   
6331  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...   
6332  Anti-Trump Protesters Are Tools of the Oligarc...   
6333  In Ethiopia, Obama seeks progress on peace, se...   
6334  Jeb Bush Is Suddenly Attacking Trump. Here's W...   

                                                   text label  
0     Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1     Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2     U.S. Secretary of State John F. Kerry said Mon...  REAL  
3     — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4     It's primary day in New York and front-runners...  REAL  
...                                                 ...   ...  
6330  The State Department told the Republican Natio...  REAL  
6331  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...  FAKE  
6332   Anti-Trump Protesters Are Tools of the Oligar...  FAKE  
6333  ADDIS ABABA, Ethiopia —President Obama convene...  REAL  
6334  Jeb Bush Is Suddenly Attacking Trump. Here's W...  REAL  

[6335 rows x 3 columns]

In [4]:
dataset.shape

(6335, 3)

### Input Output Split

In [5]:
indep_x = dataset['text']
dep_y = dataset['label']

### Train Test Split

In [6]:
x_train,x_test,y_train,y_test = train_test_split(indep_x,dep_y,test_size = 0.2, random_state = 0)

## Using Counter Vector Method
### Converting Text --> Vectors (Numbers) 

In [7]:
hash_vector = HashingVectorizer(n_features = 12, alternate_sign = False)
vectors_train = hash_vector.fit_transform(x_train)
vectors_test = hash_vector.transform(x_test)

In [8]:
print(x_train)

2402    Christian Whiton is a former deputy special en...
1922    Super Tuesday Brings Harsh Light And Heartache...
3475    Prev post Page 1 of 4 Next \nNurses are among ...
6197    The deadly hostage situation at a luxury hotel...
4748    Our new country: Women and minorities hit hard...
                              ...                        
4931    Twenty-two of the 37 corporations nominated fo...
3264    As pieces of luggage, human remains, wreckage ...
1653    0 Add Comment \nIN THE immediate aftermath of ...
2607    Palestine Palestinians check the flat of Amjad...
2732    For the second week in a row, there was a temp...
Name: text, Length: 5068, dtype: object


In [9]:
print(vectors_train)

  (0, 0)	0.48889473806308004
  (0, 1)	0.278164247518649
  (0, 2)	0.17701361205732208
  (0, 3)	0.22758892978798553
  (0, 4)	0.3329541750602011
  (0, 5)	0.3160957358166466
  (0, 6)	0.3793148829799759
  (0, 7)	0.3413833946819783
  (0, 8)	0.17279900224643346
  (0, 9)	0.17701361205732208
  (0, 10)	0.13486751394843588
  (0, 11)	0.22337431997709692
  (1, 0)	0.2887102878645391
  (1, 1)	0.3528681296122145
  (1, 2)	0.18260308805107603
  (1, 3)	0.23935810190478884
  (1, 4)	0.2911778971625266
  (1, 5)	0.3059835529504517
  (1, 6)	0.5404064362592655
  (1, 7)	0.24429332050076388
  (1, 8)	0.15052416717723835
  (1, 9)	0.19000591594503857
  (1, 10)	0.1431213392832758
  (1, 11)	0.3035159436524642
  (2, 0)	0.3321440596109373
  :	:
  (5065, 11)	0.33046627925857974
  (5066, 0)	0.3270591783093788
  (5066, 1)	0.2693428527253708
  (5066, 2)	0.21162652714136276
  (5066, 3)	0.12505203876535073
  (5066, 4)	0.20200713954402807
  (5066, 5)	0.41363366668539087
  (5066, 6)	0.5002081550614029
  (5066, 7)	0.35591734110

In [10]:
print(vectors_test)

  (0, 0)	0.2514766029145074
  (0, 1)	0.3929321920539178
  (0, 2)	0.23575931523235066
  (0, 3)	0.28605463581525215
  (0, 4)	0.27033734813309546
  (0, 5)	0.29548500842454617
  (0, 6)	0.43379714002752523
  (0, 7)	0.36778453176246706
  (0, 8)	0.21061165494089992
  (0, 9)	0.18232053711301785
  (0, 10)	0.2011812823316059
  (0, 11)	0.2074681974044686
  (1, 0)	0.23239915871656816
  (1, 1)	0.19919927889991557
  (1, 2)	0.2987989183498734
  (1, 3)	0.24899909862489447
  (1, 4)	0.33199879816652594
  (1, 5)	0.2987989183498734
  (1, 6)	0.49799819724978894
  (1, 7)	0.34859873807485225
  (1, 8)	0.08299969954163149
  (1, 9)	0.1493994591749367
  (1, 10)	0.21579921880824188
  (1, 11)	0.33199879816652594
  (2, 0)	0.351581276967315
  :	:
  (1264, 11)	0.1675235703441389
  (1265, 0)	0.23545212527210113
  (1265, 1)	0.3531781879081517
  (1265, 2)	0.16818008948007224
  (1265, 3)	0.2102251118500903
  (1265, 4)	0.2690881431681156
  (1265, 5)	0.32795117448614086
  (1265, 6)	0.4961312639662131
  (1265, 7)	0.36158719

### Check the count of features formed from the text

In [11]:
print(vectors_train.toarray())

[[0.48889474 0.27816425 0.17701361 ... 0.17701361 0.13486751 0.22337432]
 [0.28871029 0.35286813 0.18260309 ... 0.19000592 0.14312134 0.30351594]
 [0.33214406 0.36233897 0.23401059 ... 0.25665677 0.18871822 0.30194915]
 ...
 [0.33815154 0.33815154 0.1229642  ... 0.1844463  0.20750208 0.33046628]
 [0.32705918 0.26934285 0.21162653 ... 0.27896224 0.1539102  0.14429081]
 [0.2687763  0.37715385 0.15172856 ... 0.15172856 0.16473386 0.32513263]]


In [12]:
print(vectors_test.toarray())

[[0.2514766  0.39293219 0.23575932 ... 0.18232054 0.20118128 0.2074682 ]
 [0.23239916 0.19919928 0.29879892 ... 0.14939946 0.21579922 0.3319988 ]
 [0.35158128 0.29005455 0.21094877 ... 0.1933697  0.1933697  0.29884409]
 ...
 [0.33504714 0.4666728  0.26325132 ... 0.20342148 0.25128536 0.16752357]
 [0.23545213 0.35317819 0.16818009 ... 0.15977109 0.11772606 0.24386113]
 [0.29286068 0.32214675 0.1708354  ... 0.11714427 0.16107338 0.26845563]]


In [13]:
vectors_train.shape

(5068, 12)

In [14]:
vectors_test.shape

(1267, 12)

### Model Creation

### MultinomialNB

In [15]:
classifier = MultinomialNB()
classifier.fit(vectors_train, y_train)

MultinomialNB()

### Prediction

In [16]:
y_pred = classifier.predict(vectors_test)
y_pred

array(['FAKE', 'FAKE', 'FAKE', ..., 'FAKE', 'FAKE', 'FAKE'], dtype='<U4')

### Accuracy

In [17]:
accuracy = accuracy_score(y_test,y_pred)
accuracy

0.5138121546961326

### Confusion Matrix

In [18]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[563,  52],
       [564,  88]], dtype=int64)

### Classification Report

In [19]:
report = classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

        FAKE       0.50      0.92      0.65       615
        REAL       0.63      0.13      0.22       652

    accuracy                           0.51      1267
   macro avg       0.56      0.53      0.43      1267
weighted avg       0.57      0.51      0.43      1267



### Checking for the Prediction

In [20]:
dataset['text'][0]

'Daniel Greenfield, a Shillman Journalism Fellow at the Freedom Center, is a New York writer focusing on radical Islam. \nIn the final stretch of the election, Hillary Rodham Clinton has gone to war with the FBI. \nThe word “unprecedented” has been thrown around so often this election that it ought to be retired. But it’s still unprecedented for the nominee of a major political party to go war with the FBI. \nBut that’s exactly what Hillary and her people have done. Coma patients just waking up now and watching an hour of CNN from their hospital beds would assume that FBI Director James Comey is Hillary’s opponent in this election. \nThe FBI is under attack by everyone from Obama to CNN. Hillary’s people have circulated a letter attacking Comey. There are currently more media hit pieces lambasting him than targeting Trump. It wouldn’t be too surprising if the Clintons or their allies were to start running attack ads against the FBI. \nThe FBI’s leadership is being warned that the entir

In [21]:
vectors_train[[0]]

<1x12 sparse matrix of type '<class 'numpy.float64'>'
	with 12 stored elements in Compressed Sparse Row format>

In [22]:
x_train[[0]]

0    Daniel Greenfield, a Shillman Journalism Fello...
Name: text, dtype: object

In [23]:
classifier.predict(vectors_train[[0]])

array(['FAKE'], dtype='<U4')

In [24]:
vectors_train[25]

<1x12 sparse matrix of type '<class 'numpy.float64'>'
	with 12 stored elements in Compressed Sparse Row format>

In [25]:
x_train[[25]]

25    Washington (CNN) The faction of the GOP that i...
Name: text, dtype: object

In [26]:
classifier.predict(vectors_train[[25]])

array(['FAKE'], dtype='<U4')

### PassiveAggressiveClassifier Algorithm

In [27]:
Classifier = PassiveAggressiveClassifier(max_iter=1000, random_state=0)
Classifier.fit(vectors_train,y_train)

PassiveAggressiveClassifier(random_state=0)

In [28]:
y_pred = Classifier.predict(vectors_test)
y_pred

array(['FAKE', 'FAKE', 'FAKE', ..., 'FAKE', 'FAKE', 'FAKE'], dtype='<U4')

In [29]:
accuracy = accuracy_score(y_test,y_pred)
accuracy

0.5082872928176796

In [30]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[607,   8],
       [615,  37]], dtype=int64)

In [31]:
report = classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

        FAKE       0.50      0.99      0.66       615
        REAL       0.82      0.06      0.11       652

    accuracy                           0.51      1267
   macro avg       0.66      0.52      0.38      1267
weighted avg       0.66      0.51      0.38      1267



### Logistic Regression Algorithm

In [32]:
Classifier = LogisticRegression()
Classifier.fit(vectors_train,y_train)

LogisticRegression()

In [33]:
y_pred = Classifier.predict(vectors_test)
y_pred

array(['REAL', 'REAL', 'FAKE', ..., 'REAL', 'REAL', 'REAL'], dtype=object)

In [34]:
accuracy = accuracy_score(y_test,y_pred)
accuracy

0.6211523283346487

In [35]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[350, 265],
       [215, 437]], dtype=int64)

In [36]:
report = classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

        FAKE       0.62      0.57      0.59       615
        REAL       0.62      0.67      0.65       652

    accuracy                           0.62      1267
   macro avg       0.62      0.62      0.62      1267
weighted avg       0.62      0.62      0.62      1267



### KNN Algorithm

In [37]:
Classifier = KNeighborsClassifier()
Classifier.fit(vectors_train,y_train)

KNeighborsClassifier()

In [38]:
y_pred = Classifier.predict(vectors_test)
y_pred

array(['REAL', 'FAKE', 'REAL', ..., 'FAKE', 'REAL', 'FAKE'], dtype=object)

In [39]:
accuracy = accuracy_score(y_test,y_pred)

cm = confusion_matrix(y_test,y_pred)

report = classification_report(y_test,y_pred)
print('Accuracy:', accuracy, '\n',
      'Confusion Matrix:\n', cm, '\n',
      'Report:\n', report)

Accuracy: 0.6022099447513812 
 Confusion Matrix:
 [[307 308]
 [196 456]] 
 Report:
               precision    recall  f1-score   support

        FAKE       0.61      0.50      0.55       615
        REAL       0.60      0.70      0.64       652

    accuracy                           0.60      1267
   macro avg       0.60      0.60      0.60      1267
weighted avg       0.60      0.60      0.60      1267



### SVC

In [40]:
Classifier = SVC()
Classifier.fit(vectors_train,y_train)

SVC()

In [41]:
y_pred = Classifier.predict(vectors_test)
y_pred

array(['REAL', 'FAKE', 'REAL', ..., 'FAKE', 'REAL', 'REAL'], dtype=object)

In [42]:
accuracy = accuracy_score(y_test,y_pred)

cm = confusion_matrix(y_test,y_pred)

report = classification_report(y_test,y_pred)
print('Accuracy:', accuracy, '\n',
      'Confusion Matrix:\n', cm, '\n',
      'Report:\n', report)

Accuracy: 0.6779794790844514 
 Confusion Matrix:
 [[370 245]
 [163 489]] 
 Report:
               precision    recall  f1-score   support

        FAKE       0.69      0.60      0.64       615
        REAL       0.67      0.75      0.71       652

    accuracy                           0.68      1267
   macro avg       0.68      0.68      0.68      1267
weighted avg       0.68      0.68      0.68      1267



### Decision Tree Classifier

In [43]:
Classifier = DecisionTreeClassifier()
Classifier.fit(vectors_train,y_train)

DecisionTreeClassifier()

In [44]:
y_pred = Classifier.predict(vectors_test)
y_pred

array(['REAL', 'REAL', 'FAKE', ..., 'REAL', 'FAKE', 'REAL'], dtype=object)

In [45]:
accuracy = accuracy_score(y_test,y_pred)

cm = confusion_matrix(y_test,y_pred)

report = classification_report(y_test,y_pred)
print('Accuracy:', accuracy, '\n',
      'Confusion Matrix:\n', cm, '\n',
      'Report:\n', report)

Accuracy: 0.6203630623520127 
 Confusion Matrix:
 [[378 237]
 [244 408]] 
 Report:
               precision    recall  f1-score   support

        FAKE       0.61      0.61      0.61       615
        REAL       0.63      0.63      0.63       652

    accuracy                           0.62      1267
   macro avg       0.62      0.62      0.62      1267
weighted avg       0.62      0.62      0.62      1267



### Random Forest Classifier

In [46]:
Classifier = RandomForestClassifier()
Classifier.fit(vectors_train,y_train)

RandomForestClassifier()

In [47]:
y_pred = Classifier.predict(vectors_test)
y_pred

array(['REAL', 'FAKE', 'FAKE', ..., 'FAKE', 'REAL', 'REAL'], dtype=object)

In [48]:
accuracy = accuracy_score(y_test,y_pred)

cm = confusion_matrix(y_test,y_pred)

report = classification_report(y_test,y_pred)
print('Accuracy:', accuracy, '\n',
      'Confusion Matrix:\n', cm, '\n',
      'Report:\n', report)

Accuracy: 0.6921862667719021 
 Confusion Matrix:
 [[434 181]
 [209 443]] 
 Report:
               precision    recall  f1-score   support

        FAKE       0.67      0.71      0.69       615
        REAL       0.71      0.68      0.69       652

    accuracy                           0.69      1267
   macro avg       0.69      0.69      0.69      1267
weighted avg       0.69      0.69      0.69      1267

